package neuEstate.po.cpl;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class CplNeuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public CplNeuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCplidIsNull() {
            addCriterion("cplId is null");
            return (Criteria) this;
        }

        public Criteria andCplidIsNotNull() {
            addCriterion("cplId is not null");
            return (Criteria) this;
        }

        public Criteria andCplidEqualTo(BigDecimal value) {
            addCriterion("\"cplId\" =", value, "cplid");
            return (Criteria) this;
        }

        public Criteria andCplidNotEqualTo(BigDecimal value) {
            addCriterion("cplId <>", value, "cplid");
            return (Criteria) this;
        }

        public Criteria andCplidGreaterThan(BigDecimal value) {
            addCriterion("cplId >", value, "cplid");
            return (Criteria) this;
        }

        public Criteria andCplidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cplId >=", value, "cplid");
            return (Criteria) this;
        }

        public Criteria andCplidLessThan(BigDecimal value) {
            addCriterion("cplId <", value, "cplid");
            return (Criteria) this;
        }

        public Criteria andCplidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cplId <=", value, "cplid");
            return (Criteria) this;
        }

        public Criteria andCplidIn(List<BigDecimal> values) {
            addCriterion("\"cplId\" in", values, "cplid");
            return (Criteria) this;
        }

        public Criteria andCplidNotIn(List<BigDecimal> values) {
            addCriterion("cplId not in", values, "cplid");
            return (Criteria) this;
        }

        public Criteria andCplidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cplId between", value1, value2, "cplid");
            return (Criteria) this;
        }

        public Criteria andCplidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cplId not between", value1, value2, "cplid");
            return (Criteria) this;
        }

        public Criteria andCpltypeIsNull() {
            addCriterion("cplType is null");
            return (Criteria) this;
        }

        public Criteria andCpltypeIsNotNull() {
            addCriterion("cplType is not null");
            return (Criteria) this;
        }

        public Criteria andCpltypeEqualTo(String value) {
            addCriterion("cplType =", value, "cpltype");
            return (Criteria) this;
        }

        public Criteria andCpltypeNotEqualTo(String value) {
            addCriterion("cplType <>", value, "cpltype");
            return (Criteria) this;
        }

        public Criteria andCpltypeGreaterThan(String value) {
            addCriterion("cplType >", value, "cpltype");
            return (Criteria) this;
        }

        public Criteria andCpltypeGreaterThanOrEqualTo(String value) {
            addCriterion("cplType >=", value, "cpltype");
            return (Criteria) this;
        }

        public Criteria andCpltypeLessThan(String value) {
            addCriterion("cplType <", value, "cpltype");
            return (Criteria) this;
        }

        public Criteria andCpltypeLessThanOrEqualTo(String value) {
            addCriterion("cplType <=", value, "cpltype");
            return (Criteria) this;
        }

        public Criteria andCpltypeLike(String value) {
            addCriterion("cplType like", value, "cpltype");
            return (Criteria) this;
        }

        public Criteria andCpltypeNotLike(String value) {
            addCriterion("cplType not like", value, "cpltype");
            return (Criteria) this;
        }

        public Criteria andCpltypeIn(List<String> values) {
            addCriterion("cplType in", values, "cpltype");
            return (Criteria) this;
        }

        public Criteria andCpltypeNotIn(List<String> values) {
            addCriterion("cplType not in", values, "cpltype");
            return (Criteria) this;
        }

        public Criteria andCpltypeBetween(String value1, String value2) {
            addCriterion("cplType between", value1, value2, "cpltype");
            return (Criteria) this;
        }

        public Criteria andCpltypeNotBetween(String value1, String value2) {
            addCriterion("cplType not between", value1, value2, "cpltype");
            return (Criteria) this;
        }

        public Criteria andCplcontentIsNull() {
            addCriterion("cplContent is null");
            return (Criteria) this;
        }

        public Criteria andCplcontentIsNotNull() {
            addCriterion("cplContent is not null");
            return (Criteria) this;
        }

        public Criteria andCplcontentEqualTo(String value) {
            addCriterion("cplContent =", value, "cplcontent");
            return (Criteria) this;
        }

        public Criteria andCplcontentNotEqualTo(String value) {
            addCriterion("cplContent <>", value, "cplcontent");
            return (Criteria) this;
        }

        public Criteria andCplcontentGreaterThan(String value) {
            addCriterion("cplContent >", value, "cplcontent");
            return (Criteria) this;
        }

        public Criteria andCplcontentGreaterThanOrEqualTo(String value) {
            addCriterion("cplContent >=", value, "cplcontent");
            return (Criteria) this;
        }

        public Criteria andCplcontentLessThan(String value) {
            addCriterion("cplContent <", value, "cplcontent");
            return (Criteria) this;
        }

        public Criteria andCplcontentLessThanOrEqualTo(String value) {
            addCriterion("cplContent <=", value, "cplcontent");
            return (Criteria) this;
        }

        public Criteria andCplcontentLike(String value) {
            addCriterion("cplContent like", value, "cplcontent");
            return (Criteria) this;
        }

        public Criteria andCplcontentNotLike(String value) {
            addCriterion("cplContent not like", value, "cplcontent");
            return (Criteria) this;
        }

        public Criteria andCplcontentIn(List<String> values) {
            addCriterion("cplContent in", values, "cplcontent");
            return (Criteria) this;
        }

        public Criteria andCplcontentNotIn(List<String> values) {
            addCriterion("cplContent not in", values, "cplcontent");
            return (Criteria) this;
        }

        public Criteria andCplcontentBetween(String value1, String value2) {
            addCriterion("cplContent between", value1, value2, "cplcontent");
            return (Criteria) this;
        }

        public Criteria andCplcontentNotBetween(String value1, String value2) {
            addCriterion("cplContent not between", value1, value2, "cplcontent");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountIsNull() {
            addCriterion("cplHolderAccount is null");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountIsNotNull() {
            addCriterion("cplHolderAccount is not null");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountEqualTo(String value) {
            addCriterion("\"cplHolderAccount\" =", value, "cplholderaccount");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountNotEqualTo(String value) {
            addCriterion("cplHolderAccount <>", value, "cplholderaccount");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountGreaterThan(String value) {
            addCriterion("cplHolderAccount >", value, "cplholderaccount");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountGreaterThanOrEqualTo(String value) {
            addCriterion("cplHolderAccount >=", value, "cplholderaccount");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountLessThan(String value) {
            addCriterion("cplHolderAccount <", value, "cplholderaccount");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountLessThanOrEqualTo(String value) {
            addCriterion("cplHolderAccount <=", value, "cplholderaccount");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountLike(String value) {
            addCriterion("cplHolderAccount like", value, "cplholderaccount");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountNotLike(String value) {
            addCriterion("cplHolderAccount not like", value, "cplholderaccount");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountIn(List<String> values) {
            addCriterion("cplHolderAccount in", values, "cplholderaccount");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountNotIn(List<String> values) {
            addCriterion("cplHolderAccount not in", values, "cplholderaccount");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountBetween(String value1, String value2) {
            addCriterion("cplHolderAccount between", value1, value2, "cplholderaccount");
            return (Criteria) this;
        }

        public Criteria andCplholderaccountNotBetween(String value1, String value2) {
            addCriterion("cplHolderAccount not between", value1, value2, "cplholderaccount");
            return (Criteria) this;
        }

        public Criteria andCplholdernameIsNull() {
            addCriterion("cplHolderName is null");
            return (Criteria) this;
        }

        public Criteria andCplholdernameIsNotNull() {
            addCriterion("cplHolderName is not null");
            return (Criteria) this;
        }

        public Criteria andCplholdernameEqualTo(String value) {
            addCriterion("cplHolderName =", value, "cplholdername");
            return (Criteria) this;
        }

        public Criteria andCplholdernameNotEqualTo(String value) {
            addCriterion("cplHolderName <>", value, "cplholdername");
            return (Criteria) this;
        }

        public Criteria andCplholdernameGreaterThan(String value) {
            addCriterion("cplHolderName >", value, "cplholdername");
            return (Criteria) this;
        }

        public Criteria andCplholdernameGreaterThanOrEqualTo(String value) {
            addCriterion("cplHolderName >=", value, "cplholdername");
            return (Criteria) this;
        }

        public Criteria andCplholdernameLessThan(String value) {
            addCriterion("cplHolderName <", value, "cplholdername");
            return (Criteria) this;
        }

        public Criteria andCplholdernameLessThanOrEqualTo(String value) {
            addCriterion("cplHolderName <=", value, "cplholdername");
            return (Criteria) this;
        }

        public Criteria andCplholdernameLike(String value) {
            addCriterion("cplHolderName like", value, "cplholdername");
            return (Criteria) this;
        }

        public Criteria andCplholdernameNotLike(String value) {
            addCriterion("cplHolderName not like", value, "cplholdername");
            return (Criteria) this;
        }

        public Criteria andCplholdernameIn(List<String> values) {
            addCriterion("cplHolderName in", values, "cplholdername");
            return (Criteria) this;
        }

        public Criteria andCplholdernameNotIn(List<String> values) {
            addCriterion("cplHolderName not in", values, "cplholdername");
            return (Criteria) this;
        }

        public Criteria andCplholdernameBetween(String value1, String value2) {
            addCriterion("cplHolderName between", value1, value2, "cplholdername");
            return (Criteria) this;
        }

        public Criteria andCplholdernameNotBetween(String value1, String value2) {
            addCriterion("cplHolderName not between", value1, value2, "cplholdername");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberIsNull() {
            addCriterion("cplHolderPhoneNumber is null");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberIsNotNull() {
            addCriterion("cplHolderPhoneNumber is not null");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberEqualTo(String value) {
            addCriterion("cplHolderPhoneNumber =", value, "cplholderphonenumber");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberNotEqualTo(String value) {
            addCriterion("cplHolderPhoneNumber <>", value, "cplholderphonenumber");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberGreaterThan(String value) {
            addCriterion("cplHolderPhoneNumber >", value, "cplholderphonenumber");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberGreaterThanOrEqualTo(String value) {
            addCriterion("cplHolderPhoneNumber >=", value, "cplholderphonenumber");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberLessThan(String value) {
            addCriterion("cplHolderPhoneNumber <", value, "cplholderphonenumber");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberLessThanOrEqualTo(String value) {
            addCriterion("cplHolderPhoneNumber <=", value, "cplholderphonenumber");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberLike(String value) {
            addCriterion("cplHolderPhoneNumber like", value, "cplholderphonenumber");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberNotLike(String value) {
            addCriterion("cplHolderPhoneNumber not like", value, "cplholderphonenumber");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberIn(List<String> values) {
            addCriterion("cplHolderPhoneNumber in", values, "cplholderphonenumber");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberNotIn(List<String> values) {
            addCriterion("cplHolderPhoneNumber not in", values, "cplholderphonenumber");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberBetween(String value1, String value2) {
            addCriterion("cplHolderPhoneNumber between", value1, value2, "cplholderphonenumber");
            return (Criteria) this;
        }

        public Criteria andCplholderphonenumberNotBetween(String value1, String value2) {
            addCriterion("cplHolderPhoneNumber not between", value1, value2, "cplholderphonenumber");
            return (Criteria) this;
        }

        public Criteria andCpltimeIsNull() {
            addCriterion("cplTime is null");
            return (Criteria) this;
        }

        public Criteria andCpltimeIsNotNull() {
            addCriterion("cplTime is not null");
            return (Criteria) this;
        }

        public Criteria andCpltimeEqualTo(String value) {
            addCriterion("cplTime =", value, "cpltime");
            return (Criteria) this;
        }

        public Criteria andCpltimeNotEqualTo(String value) {
            addCriterion("cplTime <>", value, "cpltime");
            return (Criteria) this;
        }

        public Criteria andCpltimeGreaterThan(String value) {
            addCriterion("cplTime >", value, "cpltime");
            return (Criteria) this;
        }

        public Criteria andCpltimeGreaterThanOrEqualTo(String value) {
            addCriterion("cplTime >=", value, "cpltime");
            return (Criteria) this;
        }

        public Criteria andCpltimeLessThan(String value) {
            addCriterion("cplTime <", value, "cpltime");
            return (Criteria) this;
        }

        public Criteria andCpltimeLessThanOrEqualTo(String value) {
            addCriterion("cplTime <=", value, "cpltime");
            return (Criteria) this;
        }

        public Criteria andCpltimeLike(String value) {
            addCriterion("cplTime like", value, "cpltime");
            return (Criteria) this;
        }

        public Criteria andCpltimeNotLike(String value) {
            addCriterion("cplTime not like", value, "cpltime");
            return (Criteria) this;
        }

        public Criteria andCpltimeIn(List<String> values) {
            addCriterion("cplTime in", values, "cpltime");
            return (Criteria) this;
        }

        public Criteria andCpltimeNotIn(List<String> values) {
            addCriterion("cplTime not in", values, "cpltime");
            return (Criteria) this;
        }

        public Criteria andCpltimeBetween(String value1, String value2) {
            addCriterion("cplTime between", value1, value2, "cpltime");
            return (Criteria) this;
        }

        public Criteria andCpltimeNotBetween(String value1, String value2) {
            addCriterion("cplTime not between", value1, value2, "cpltime");
            return (Criteria) this;
        }

        public Criteria andCplsolveIsNull() {
            addCriterion("cplSolve is null");
            return (Criteria) this;
        }

        public Criteria andCplsolveIsNotNull() {
            addCriterion("cplSolve is not null");
            return (Criteria) this;
        }

        public Criteria andCplsolveEqualTo(String value) {
            addCriterion("\"cplSolve\" =", value, "cplsolve");
            return (Criteria) this;
        }

        public Criteria andCplsolveNotEqualTo(String value) {
            addCriterion("cplSolve <>", value, "cplsolve");
            return (Criteria) this;
        }

        public Criteria andCplsolveGreaterThan(String value) {
            addCriterion("cplSolve >", value, "cplsolve");
            return (Criteria) this;
        }

        public Criteria andCplsolveGreaterThanOrEqualTo(String value) {
            addCriterion("cplSolve >=", value, "cplsolve");
            return (Criteria) this;
        }

        public Criteria andCplsolveLessThan(String value) {
            addCriterion("cplSolve <", value, "cplsolve");
            return (Criteria) this;
        }

        public Criteria andCplsolveLessThanOrEqualTo(String value) {
            addCriterion("cplSolve <=", value, "cplsolve");
            return (Criteria) this;
        }

        public Criteria andCplsolveLike(String value) {
            addCriterion("cplSolve like", value, "cplsolve");
            return (Criteria) this;
        }

        public Criteria andCplsolveNotLike(String value) {
            addCriterion("cplSolve not like", value, "cplsolve");
            return (Criteria) this;
        }

        public Criteria andCplsolveIn(List<String> values) {
            addCriterion("cplSolve in", values, "cplsolve");
            return (Criteria) this;
        }

        public Criteria andCplsolveNotIn(List<String> values) {
            addCriterion("cplSolve not in", values, "cplsolve");
            return (Criteria) this;
        }

        public Criteria andCplsolveBetween(String value1, String value2) {
            addCriterion("cplSolve between", value1, value2, "cplsolve");
            return (Criteria) this;
        }

        public Criteria andCplsolveNotBetween(String value1, String value2) {
            addCriterion("cplSolve not between", value1, value2, "cplsolve");
            return (Criteria) this;
        }

        public Criteria andCplreplyIsNull() {
            addCriterion("cplReply is null");
            return (Criteria) this;
        }

        public Criteria andCplreplyIsNotNull() {
            addCriterion("cplReply is not null");
            return (Criteria) this;
        }

        public Criteria andCplreplyEqualTo(String value) {
            addCriterion("cplReply =", value, "cplreply");
            return (Criteria) this;
        }

        public Criteria andCplreplyNotEqualTo(String value) {
            addCriterion("cplReply <>", value, "cplreply");
            return (Criteria) this;
        }

        public Criteria andCplreplyGreaterThan(String value) {
            addCriterion("cplReply >", value, "cplreply");
            return (Criteria) this;
        }

        public Criteria andCplreplyGreaterThanOrEqualTo(String value) {
            addCriterion("cplReply >=", value, "cplreply");
            return (Criteria) this;
        }

        public Criteria andCplreplyLessThan(String value) {
            addCriterion("cplReply <", value, "cplreply");
            return (Criteria) this;
        }

        public Criteria andCplreplyLessThanOrEqualTo(String value) {
            addCriterion("cplReply <=", value, "cplreply");
            return (Criteria) this;
        }

        public Criteria andCplreplyLike(String value) {
            addCriterion("cplReply like", value, "cplreply");
            return (Criteria) this;
        }

        public Criteria andCplreplyNotLike(String value) {
            addCriterion("cplReply not like", value, "cplreply");
            return (Criteria) this;
        }

        public Criteria andCplreplyIn(List<String> values) {
            addCriterion("cplReply in", values, "cplreply");
            return (Criteria) this;
        }

        public Criteria andCplreplyNotIn(List<String> values) {
            addCriterion("cplReply not in", values, "cplreply");
            return (Criteria) this;
        }

        public Criteria andCplreplyBetween(String value1, String value2) {
            addCriterion("cplReply between", value1, value2, "cplreply");
            return (Criteria) this;
        }

        public Criteria andCplreplyNotBetween(String value1, String value2) {
            addCriterion("cplReply not between", value1, value2, "cplreply");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CPL_NEU
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 06 04:10:25 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}