package neuEstate.po.cpl;

import java.math.BigDecimal;

public class CplNeu {
    //用于分页的page当前页和rows所需行数
    private Integer startNum;
    private Integer addNum;

    public Integer getStartNum() {
        return startNum;
    }

    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    public Integer getAddNum() {
        return addNum;
    }

    public void setAddNum(Integer addNum) {
        this.addNum = addNum;
    }
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPL_NEU.cplId
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    private BigDecimal cplid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPL_NEU.cplType
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    private String cpltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPL_NEU.cplContent
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    private String cplcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPL_NEU.cplHolderAccount
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    private String cplholderaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPL_NEU.cplHolderName
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    private String cplholdername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPL_NEU.cplHolderPhoneNumber
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    private String cplholderphonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPL_NEU.cplTime
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    private String cpltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPL_NEU.cplSolve
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    private String cplsolve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPL_NEU.cplReply
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    private String cplreply;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPL_NEU.cplId
     *
     * @return the value of CPL_NEU.cplId
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public BigDecimal getCplid() {
        return cplid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPL_NEU.cplId
     *
     * @param cplid the value for CPL_NEU.cplId
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void setCplid(BigDecimal cplid) {
        this.cplid = cplid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPL_NEU.cplType
     *
     * @return the value of CPL_NEU.cplType
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public String getCpltype() {
        return cpltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPL_NEU.cplType
     *
     * @param cpltype the value for CPL_NEU.cplType
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void setCpltype(String cpltype) {
        this.cpltype = cpltype == null ? null : cpltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPL_NEU.cplContent
     *
     * @return the value of CPL_NEU.cplContent
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public String getCplcontent() {
        return cplcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPL_NEU.cplContent
     *
     * @param cplcontent the value for CPL_NEU.cplContent
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void setCplcontent(String cplcontent) {
        this.cplcontent = cplcontent == null ? null : cplcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPL_NEU.cplHolderAccount
     *
     * @return the value of CPL_NEU.cplHolderAccount
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public String getCplholderaccount() {
        return cplholderaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPL_NEU.cplHolderAccount
     *
     * @param cplholderaccount the value for CPL_NEU.cplHolderAccount
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void setCplholderaccount(String cplholderaccount) {
        this.cplholderaccount = cplholderaccount == null ? null : cplholderaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPL_NEU.cplHolderName
     *
     * @return the value of CPL_NEU.cplHolderName
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public String getCplholdername() {
        return cplholdername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPL_NEU.cplHolderName
     *
     * @param cplholdername the value for CPL_NEU.cplHolderName
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void setCplholdername(String cplholdername) {
        this.cplholdername = cplholdername == null ? null : cplholdername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPL_NEU.cplHolderPhoneNumber
     *
     * @return the value of CPL_NEU.cplHolderPhoneNumber
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public String getCplholderphonenumber() {
        return cplholderphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPL_NEU.cplHolderPhoneNumber
     *
     * @param cplholderphonenumber the value for CPL_NEU.cplHolderPhoneNumber
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void setCplholderphonenumber(String cplholderphonenumber) {
        this.cplholderphonenumber = cplholderphonenumber == null ? null : cplholderphonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPL_NEU.cplTime
     *
     * @return the value of CPL_NEU.cplTime
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public String getCpltime() {
        return cpltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPL_NEU.cplTime
     *
     * @param cpltime the value for CPL_NEU.cplTime
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void setCpltime(String cpltime) {
        this.cpltime = cpltime == null ? null : cpltime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPL_NEU.cplSolve
     *
     * @return the value of CPL_NEU.cplSolve
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public String getCplsolve() {
        return cplsolve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPL_NEU.cplSolve
     *
     * @param cplsolve the value for CPL_NEU.cplSolve
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void setCplsolve(String cplsolve) {
        this.cplsolve = cplsolve == null ? null : cplsolve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPL_NEU.cplReply
     *
     * @return the value of CPL_NEU.cplReply
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public String getCplreply() {
        return cplreply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPL_NEU.cplReply
     *
     * @param cplreply the value for CPL_NEU.cplReply
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    public void setCplreply(String cplreply) {
        this.cplreply = cplreply == null ? null : cplreply.trim();
    }
}