package neuEstate.dao.mapper.cpl;

import neuEstate.po.cpl.CplNeu;
import neuEstate.po.cpl.CplNeuExample;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface CplNeuMapper {
    List<CplNeu> selectByVagueCplHolderName(CplNeu cplNeu);
    int countByVagueCplHolderName(CplNeu cplNeu);
    List<CplNeu> selectByVagueCplType(CplNeu cplNeu);
    int countByVagueCplType(CplNeu cplNeu);
    List<CplNeu> selectByVagueDouble(CplNeu cplNeu);
    int countByVagueDouble(CplNeu cplNeu);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    int countByExample(CplNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    int deleteByExample(CplNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal cplid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    int insert(CplNeu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    int insertSelective(CplNeu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    List<CplNeu> selectByExample(CplNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    CplNeu selectByPrimaryKey(BigDecimal cplid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") CplNeu record, @Param("example") CplNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    int updateByExample(@Param("record") CplNeu record, @Param("example") CplNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    int updateByPrimaryKeySelective(CplNeu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPL_NEU
     *
     * @mbggenerated Sun Aug 06 04:10:25 CST 2017
     */
    int updateByPrimaryKey(CplNeu record);
}