package neuEstate.dao.mapper.account;

import neuEstate.po.account.UserNeu;
import neuEstate.po.account.UserNeuExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserNeuMapper {
    List<UserNeu> selectByVagueUserAccount(UserNeu userNeu);
    int countByVagueUserAccount(UserNeu userNeu);
    List<UserNeu> selectByVagueUserName(UserNeu userNeu);
    int countByVagueUserName(UserNeu userNeu);
    List<UserNeu> selectByVagueDouble(UserNeu userNeu);
    int countByVagueDouble(UserNeu userNeu);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_NEU
     *
     * @mbggenerated Sun Jul 30 22:26:32 CST 2017
     */
    int countByExample(UserNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_NEU
     *
     * @mbggenerated Sun Jul 30 22:26:32 CST 2017
     */
    int deleteByExample(UserNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_NEU
     *
     * @mbggenerated Sun Jul 30 22:26:32 CST 2017
     */
    int deleteByPrimaryKey(String useraccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_NEU
     *
     * @mbggenerated Sun Jul 30 22:26:32 CST 2017
     */
    int insert(UserNeu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_NEU
     *
     * @mbggenerated Sun Jul 30 22:26:32 CST 2017
     */
    int insertSelective(UserNeu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_NEU
     *
     * @mbggenerated Sun Jul 30 22:26:32 CST 2017
     */
    List<UserNeu> selectByExample(UserNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_NEU
     *
     * @mbggenerated Sun Jul 30 22:26:32 CST 2017
     */
    UserNeu selectByPrimaryKey(String useraccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_NEU
     *
     * @mbggenerated Sun Jul 30 22:26:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserNeu record, @Param("example") UserNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_NEU
     *
     * @mbggenerated Sun Jul 30 22:26:32 CST 2017
     */
    int updateByExample(@Param("record") UserNeu record, @Param("example") UserNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_NEU
     *
     * @mbggenerated Sun Jul 30 22:26:32 CST 2017
     */
    int updateByPrimaryKeySelective(UserNeu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_NEU
     *
     * @mbggenerated Sun Jul 30 22:26:32 CST 2017
     */
    int updateByPrimaryKey(UserNeu record);
}