package neuEstate.dao.mapper.room;

import neuEstate.po.account.UserNeu;
import neuEstate.po.room.RoomNeu;
import neuEstate.po.room.RoomNeuExample;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface RoomNeuMapper {
    List<UserNeu> selectByVagueRoomDoor(RoomNeu roomNeu);
    int countByVagueRoomDoor(RoomNeu roomNeu);
    List<UserNeu> selectByVagueRoomHolderName(RoomNeu roomNeu);
    int countByVagueRoomHolderName(RoomNeu roomNeu);
    List<UserNeu> selectByVagueDouble(RoomNeu roomNeu);
    int countByVagueDouble(RoomNeu roomNeu);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    int countByExample(RoomNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    int deleteByExample(RoomNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    int insert(RoomNeu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    int insertSelective(RoomNeu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    List<RoomNeu> selectByExample(RoomNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    RoomNeu selectByPrimaryKey(BigDecimal roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") RoomNeu record, @Param("example") RoomNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    int updateByExample(@Param("record") RoomNeu record, @Param("example") RoomNeuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    int updateByPrimaryKeySelective(RoomNeu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    int updateByPrimaryKey(RoomNeu record);
}