package neuEstate.po.room;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RoomNeuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public RoomNeuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoomidIsNull() {
            addCriterion("roomId is null");
            return (Criteria) this;
        }

        public Criteria andRoomidIsNotNull() {
            addCriterion("roomId is not null");
            return (Criteria) this;
        }

        public Criteria andRoomidEqualTo(BigDecimal value) {
            addCriterion("\"roomId\" =", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotEqualTo(BigDecimal value) {
            addCriterion("roomId <>", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidGreaterThan(BigDecimal value) {
            addCriterion("roomId >", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("roomId >=", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLessThan(BigDecimal value) {
            addCriterion("roomId <", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("roomId <=", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidIn(List<BigDecimal> values) {
            addCriterion("\"roomId\" in", values, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotIn(List<BigDecimal> values) {
            addCriterion("roomId not in", values, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("roomId between", value1, value2, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("roomId not between", value1, value2, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoombuildingIsNull() {
            addCriterion("roomBuilding is null");
            return (Criteria) this;
        }

        public Criteria andRoombuildingIsNotNull() {
            addCriterion("roomBuilding is not null");
            return (Criteria) this;
        }

        public Criteria andRoombuildingEqualTo(String value) {
            addCriterion("roomBuilding =", value, "roombuilding");
            return (Criteria) this;
        }

        public Criteria andRoombuildingNotEqualTo(String value) {
            addCriterion("roomBuilding <>", value, "roombuilding");
            return (Criteria) this;
        }

        public Criteria andRoombuildingGreaterThan(String value) {
            addCriterion("roomBuilding >", value, "roombuilding");
            return (Criteria) this;
        }

        public Criteria andRoombuildingGreaterThanOrEqualTo(String value) {
            addCriterion("roomBuilding >=", value, "roombuilding");
            return (Criteria) this;
        }

        public Criteria andRoombuildingLessThan(String value) {
            addCriterion("roomBuilding <", value, "roombuilding");
            return (Criteria) this;
        }

        public Criteria andRoombuildingLessThanOrEqualTo(String value) {
            addCriterion("roomBuilding <=", value, "roombuilding");
            return (Criteria) this;
        }

        public Criteria andRoombuildingLike(String value) {
            addCriterion("roomBuilding like", value, "roombuilding");
            return (Criteria) this;
        }

        public Criteria andRoombuildingNotLike(String value) {
            addCriterion("roomBuilding not like", value, "roombuilding");
            return (Criteria) this;
        }

        public Criteria andRoombuildingIn(List<String> values) {
            addCriterion("roomBuilding in", values, "roombuilding");
            return (Criteria) this;
        }

        public Criteria andRoombuildingNotIn(List<String> values) {
            addCriterion("roomBuilding not in", values, "roombuilding");
            return (Criteria) this;
        }

        public Criteria andRoombuildingBetween(String value1, String value2) {
            addCriterion("roomBuilding between", value1, value2, "roombuilding");
            return (Criteria) this;
        }

        public Criteria andRoombuildingNotBetween(String value1, String value2) {
            addCriterion("roomBuilding not between", value1, value2, "roombuilding");
            return (Criteria) this;
        }

        public Criteria andRoomfloorIsNull() {
            addCriterion("roomFloor is null");
            return (Criteria) this;
        }

        public Criteria andRoomfloorIsNotNull() {
            addCriterion("roomFloor is not null");
            return (Criteria) this;
        }

        public Criteria andRoomfloorEqualTo(String value) {
            addCriterion("roomFloor =", value, "roomfloor");
            return (Criteria) this;
        }

        public Criteria andRoomfloorNotEqualTo(String value) {
            addCriterion("roomFloor <>", value, "roomfloor");
            return (Criteria) this;
        }

        public Criteria andRoomfloorGreaterThan(String value) {
            addCriterion("roomFloor >", value, "roomfloor");
            return (Criteria) this;
        }

        public Criteria andRoomfloorGreaterThanOrEqualTo(String value) {
            addCriterion("roomFloor >=", value, "roomfloor");
            return (Criteria) this;
        }

        public Criteria andRoomfloorLessThan(String value) {
            addCriterion("roomFloor <", value, "roomfloor");
            return (Criteria) this;
        }

        public Criteria andRoomfloorLessThanOrEqualTo(String value) {
            addCriterion("roomFloor <=", value, "roomfloor");
            return (Criteria) this;
        }

        public Criteria andRoomfloorLike(String value) {
            addCriterion("roomFloor like", value, "roomfloor");
            return (Criteria) this;
        }

        public Criteria andRoomfloorNotLike(String value) {
            addCriterion("roomFloor not like", value, "roomfloor");
            return (Criteria) this;
        }

        public Criteria andRoomfloorIn(List<String> values) {
            addCriterion("roomFloor in", values, "roomfloor");
            return (Criteria) this;
        }

        public Criteria andRoomfloorNotIn(List<String> values) {
            addCriterion("roomFloor not in", values, "roomfloor");
            return (Criteria) this;
        }

        public Criteria andRoomfloorBetween(String value1, String value2) {
            addCriterion("roomFloor between", value1, value2, "roomfloor");
            return (Criteria) this;
        }

        public Criteria andRoomfloorNotBetween(String value1, String value2) {
            addCriterion("roomFloor not between", value1, value2, "roomfloor");
            return (Criteria) this;
        }

        public Criteria andRoomdoorIsNull() {
            addCriterion("roomDoor is null");
            return (Criteria) this;
        }

        public Criteria andRoomdoorIsNotNull() {
            addCriterion("roomDoor is not null");
            return (Criteria) this;
        }

        public Criteria andRoomdoorEqualTo(String value) {
            addCriterion("roomDoor =", value, "roomdoor");
            return (Criteria) this;
        }

        public Criteria andRoomdoorNotEqualTo(String value) {
            addCriterion("roomDoor <>", value, "roomdoor");
            return (Criteria) this;
        }

        public Criteria andRoomdoorGreaterThan(String value) {
            addCriterion("roomDoor >", value, "roomdoor");
            return (Criteria) this;
        }

        public Criteria andRoomdoorGreaterThanOrEqualTo(String value) {
            addCriterion("roomDoor >=", value, "roomdoor");
            return (Criteria) this;
        }

        public Criteria andRoomdoorLessThan(String value) {
            addCriterion("roomDoor <", value, "roomdoor");
            return (Criteria) this;
        }

        public Criteria andRoomdoorLessThanOrEqualTo(String value) {
            addCriterion("roomDoor <=", value, "roomdoor");
            return (Criteria) this;
        }

        public Criteria andRoomdoorLike(String value) {
            addCriterion("roomDoor like", value, "roomdoor");
            return (Criteria) this;
        }

        public Criteria andRoomdoorNotLike(String value) {
            addCriterion("roomDoor not like", value, "roomdoor");
            return (Criteria) this;
        }

        public Criteria andRoomdoorIn(List<String> values) {
            addCriterion("roomDoor in", values, "roomdoor");
            return (Criteria) this;
        }

        public Criteria andRoomdoorNotIn(List<String> values) {
            addCriterion("roomDoor not in", values, "roomdoor");
            return (Criteria) this;
        }

        public Criteria andRoomdoorBetween(String value1, String value2) {
            addCriterion("roomDoor between", value1, value2, "roomdoor");
            return (Criteria) this;
        }

        public Criteria andRoomdoorNotBetween(String value1, String value2) {
            addCriterion("roomDoor not between", value1, value2, "roomdoor");
            return (Criteria) this;
        }

        public Criteria andRoomareaIsNull() {
            addCriterion("roomArea is null");
            return (Criteria) this;
        }

        public Criteria andRoomareaIsNotNull() {
            addCriterion("roomArea is not null");
            return (Criteria) this;
        }

        public Criteria andRoomareaEqualTo(String value) {
            addCriterion("roomArea =", value, "roomarea");
            return (Criteria) this;
        }

        public Criteria andRoomareaNotEqualTo(String value) {
            addCriterion("roomArea <>", value, "roomarea");
            return (Criteria) this;
        }

        public Criteria andRoomareaGreaterThan(String value) {
            addCriterion("roomArea >", value, "roomarea");
            return (Criteria) this;
        }

        public Criteria andRoomareaGreaterThanOrEqualTo(String value) {
            addCriterion("roomArea >=", value, "roomarea");
            return (Criteria) this;
        }

        public Criteria andRoomareaLessThan(String value) {
            addCriterion("roomArea <", value, "roomarea");
            return (Criteria) this;
        }

        public Criteria andRoomareaLessThanOrEqualTo(String value) {
            addCriterion("roomArea <=", value, "roomarea");
            return (Criteria) this;
        }

        public Criteria andRoomareaLike(String value) {
            addCriterion("roomArea like", value, "roomarea");
            return (Criteria) this;
        }

        public Criteria andRoomareaNotLike(String value) {
            addCriterion("roomArea not like", value, "roomarea");
            return (Criteria) this;
        }

        public Criteria andRoomareaIn(List<String> values) {
            addCriterion("roomArea in", values, "roomarea");
            return (Criteria) this;
        }

        public Criteria andRoomareaNotIn(List<String> values) {
            addCriterion("roomArea not in", values, "roomarea");
            return (Criteria) this;
        }

        public Criteria andRoomareaBetween(String value1, String value2) {
            addCriterion("roomArea between", value1, value2, "roomarea");
            return (Criteria) this;
        }

        public Criteria andRoomareaNotBetween(String value1, String value2) {
            addCriterion("roomArea not between", value1, value2, "roomarea");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountIsNull() {
            addCriterion("roomHolderAccount is null");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountIsNotNull() {
            addCriterion("roomHolderAccount is not null");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountEqualTo(String value) {
            addCriterion("\"roomHolderAccount\" =", value, "roomholderaccount");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountNotEqualTo(String value) {
            addCriterion("roomHolderAccount <>", value, "roomholderaccount");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountGreaterThan(String value) {
            addCriterion("roomHolderAccount >", value, "roomholderaccount");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountGreaterThanOrEqualTo(String value) {
            addCriterion("roomHolderAccount >=", value, "roomholderaccount");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountLessThan(String value) {
            addCriterion("roomHolderAccount <", value, "roomholderaccount");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountLessThanOrEqualTo(String value) {
            addCriterion("roomHolderAccount <=", value, "roomholderaccount");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountLike(String value) {
            addCriterion("roomHolderAccount like", value, "roomholderaccount");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountNotLike(String value) {
            addCriterion("roomHolderAccount not like", value, "roomholderaccount");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountIn(List<String> values) {
            addCriterion("roomHolderAccount in", values, "roomholderaccount");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountNotIn(List<String> values) {
            addCriterion("roomHolderAccount not in", values, "roomholderaccount");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountBetween(String value1, String value2) {
            addCriterion("roomHolderAccount between", value1, value2, "roomholderaccount");
            return (Criteria) this;
        }

        public Criteria andRoomholderaccountNotBetween(String value1, String value2) {
            addCriterion("roomHolderAccount not between", value1, value2, "roomholderaccount");
            return (Criteria) this;
        }

        public Criteria andRoomwaterIsNull() {
            addCriterion("roomWater is null");
            return (Criteria) this;
        }

        public Criteria andRoomwaterIsNotNull() {
            addCriterion("roomWater is not null");
            return (Criteria) this;
        }

        public Criteria andRoomwaterEqualTo(String value) {
            addCriterion("roomWater =", value, "roomwater");
            return (Criteria) this;
        }

        public Criteria andRoomwaterNotEqualTo(String value) {
            addCriterion("roomWater <>", value, "roomwater");
            return (Criteria) this;
        }

        public Criteria andRoomwaterGreaterThan(String value) {
            addCriterion("roomWater >", value, "roomwater");
            return (Criteria) this;
        }

        public Criteria andRoomwaterGreaterThanOrEqualTo(String value) {
            addCriterion("roomWater >=", value, "roomwater");
            return (Criteria) this;
        }

        public Criteria andRoomwaterLessThan(String value) {
            addCriterion("roomWater <", value, "roomwater");
            return (Criteria) this;
        }

        public Criteria andRoomwaterLessThanOrEqualTo(String value) {
            addCriterion("roomWater <=", value, "roomwater");
            return (Criteria) this;
        }

        public Criteria andRoomwaterLike(String value) {
            addCriterion("roomWater like", value, "roomwater");
            return (Criteria) this;
        }

        public Criteria andRoomwaterNotLike(String value) {
            addCriterion("roomWater not like", value, "roomwater");
            return (Criteria) this;
        }

        public Criteria andRoomwaterIn(List<String> values) {
            addCriterion("roomWater in", values, "roomwater");
            return (Criteria) this;
        }

        public Criteria andRoomwaterNotIn(List<String> values) {
            addCriterion("roomWater not in", values, "roomwater");
            return (Criteria) this;
        }

        public Criteria andRoomwaterBetween(String value1, String value2) {
            addCriterion("roomWater between", value1, value2, "roomwater");
            return (Criteria) this;
        }

        public Criteria andRoomwaterNotBetween(String value1, String value2) {
            addCriterion("roomWater not between", value1, value2, "roomwater");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityIsNull() {
            addCriterion("roomElectrcity is null");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityIsNotNull() {
            addCriterion("roomElectrcity is not null");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityEqualTo(String value) {
            addCriterion("roomElectrcity =", value, "roomelectrcity");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityNotEqualTo(String value) {
            addCriterion("roomElectrcity <>", value, "roomelectrcity");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityGreaterThan(String value) {
            addCriterion("roomElectrcity >", value, "roomelectrcity");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityGreaterThanOrEqualTo(String value) {
            addCriterion("roomElectrcity >=", value, "roomelectrcity");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityLessThan(String value) {
            addCriterion("roomElectrcity <", value, "roomelectrcity");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityLessThanOrEqualTo(String value) {
            addCriterion("roomElectrcity <=", value, "roomelectrcity");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityLike(String value) {
            addCriterion("roomElectrcity like", value, "roomelectrcity");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityNotLike(String value) {
            addCriterion("roomElectrcity not like", value, "roomelectrcity");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityIn(List<String> values) {
            addCriterion("roomElectrcity in", values, "roomelectrcity");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityNotIn(List<String> values) {
            addCriterion("roomElectrcity not in", values, "roomelectrcity");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityBetween(String value1, String value2) {
            addCriterion("roomElectrcity between", value1, value2, "roomelectrcity");
            return (Criteria) this;
        }

        public Criteria andRoomelectrcityNotBetween(String value1, String value2) {
            addCriterion("roomElectrcity not between", value1, value2, "roomelectrcity");
            return (Criteria) this;
        }

        public Criteria andRoomgasIsNull() {
            addCriterion("roomGas is null");
            return (Criteria) this;
        }

        public Criteria andRoomgasIsNotNull() {
            addCriterion("roomGas is not null");
            return (Criteria) this;
        }

        public Criteria andRoomgasEqualTo(String value) {
            addCriterion("roomGas =", value, "roomgas");
            return (Criteria) this;
        }

        public Criteria andRoomgasNotEqualTo(String value) {
            addCriterion("roomGas <>", value, "roomgas");
            return (Criteria) this;
        }

        public Criteria andRoomgasGreaterThan(String value) {
            addCriterion("roomGas >", value, "roomgas");
            return (Criteria) this;
        }

        public Criteria andRoomgasGreaterThanOrEqualTo(String value) {
            addCriterion("roomGas >=", value, "roomgas");
            return (Criteria) this;
        }

        public Criteria andRoomgasLessThan(String value) {
            addCriterion("roomGas <", value, "roomgas");
            return (Criteria) this;
        }

        public Criteria andRoomgasLessThanOrEqualTo(String value) {
            addCriterion("roomGas <=", value, "roomgas");
            return (Criteria) this;
        }

        public Criteria andRoomgasLike(String value) {
            addCriterion("roomGas like", value, "roomgas");
            return (Criteria) this;
        }

        public Criteria andRoomgasNotLike(String value) {
            addCriterion("roomGas not like", value, "roomgas");
            return (Criteria) this;
        }

        public Criteria andRoomgasIn(List<String> values) {
            addCriterion("roomGas in", values, "roomgas");
            return (Criteria) this;
        }

        public Criteria andRoomgasNotIn(List<String> values) {
            addCriterion("roomGas not in", values, "roomgas");
            return (Criteria) this;
        }

        public Criteria andRoomgasBetween(String value1, String value2) {
            addCriterion("roomGas between", value1, value2, "roomgas");
            return (Criteria) this;
        }

        public Criteria andRoomgasNotBetween(String value1, String value2) {
            addCriterion("roomGas not between", value1, value2, "roomgas");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeIsNull() {
            addCriterion("roomEstatefee is null");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeIsNotNull() {
            addCriterion("roomEstatefee is not null");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeEqualTo(String value) {
            addCriterion("roomEstatefee =", value, "roomestatefee");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeNotEqualTo(String value) {
            addCriterion("roomEstatefee <>", value, "roomestatefee");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeGreaterThan(String value) {
            addCriterion("roomEstatefee >", value, "roomestatefee");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeGreaterThanOrEqualTo(String value) {
            addCriterion("roomEstatefee >=", value, "roomestatefee");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeLessThan(String value) {
            addCriterion("roomEstatefee <", value, "roomestatefee");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeLessThanOrEqualTo(String value) {
            addCriterion("roomEstatefee <=", value, "roomestatefee");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeLike(String value) {
            addCriterion("roomEstatefee like", value, "roomestatefee");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeNotLike(String value) {
            addCriterion("roomEstatefee not like", value, "roomestatefee");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeIn(List<String> values) {
            addCriterion("roomEstatefee in", values, "roomestatefee");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeNotIn(List<String> values) {
            addCriterion("roomEstatefee not in", values, "roomestatefee");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeBetween(String value1, String value2) {
            addCriterion("roomEstatefee between", value1, value2, "roomestatefee");
            return (Criteria) this;
        }

        public Criteria andRoomestatefeeNotBetween(String value1, String value2) {
            addCriterion("roomEstatefee not between", value1, value2, "roomestatefee");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameIsNull() {
            addCriterion("roomHolderName is null");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameIsNotNull() {
            addCriterion("roomHolderName is not null");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameEqualTo(String value) {
            addCriterion("roomHolderName =", value, "roomholdername");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameNotEqualTo(String value) {
            addCriterion("roomHolderName <>", value, "roomholdername");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameGreaterThan(String value) {
            addCriterion("roomHolderName >", value, "roomholdername");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameGreaterThanOrEqualTo(String value) {
            addCriterion("roomHolderName >=", value, "roomholdername");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameLessThan(String value) {
            addCriterion("roomHolderName <", value, "roomholdername");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameLessThanOrEqualTo(String value) {
            addCriterion("roomHolderName <=", value, "roomholdername");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameLike(String value) {
            addCriterion("roomHolderName like", value, "roomholdername");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameNotLike(String value) {
            addCriterion("roomHolderName not like", value, "roomholdername");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameIn(List<String> values) {
            addCriterion("roomHolderName in", values, "roomholdername");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameNotIn(List<String> values) {
            addCriterion("roomHolderName not in", values, "roomholdername");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameBetween(String value1, String value2) {
            addCriterion("roomHolderName between", value1, value2, "roomholdername");
            return (Criteria) this;
        }

        public Criteria andRoomholdernameNotBetween(String value1, String value2) {
            addCriterion("roomHolderName not between", value1, value2, "roomholdername");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ROOM_NEU
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 01 20:04:15 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ROOM_NEU
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}