package neuEstate.po.room;

import java.math.BigDecimal;

public class RoomNeu {
    //用于分页的page当前页和rows所需行数
    private Integer startNum;
    private Integer addNum;

    public Integer getStartNum() {
        return startNum;
    }

    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    public Integer getAddNum() {
        return addNum;
    }

    public void setAddNum(Integer addNum) {
        this.addNum = addNum;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_NEU.roomId
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    private BigDecimal roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_NEU.roomBuilding
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    private String roombuilding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_NEU.roomFloor
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    private String roomfloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_NEU.roomDoor
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    private String roomdoor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_NEU.roomArea
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    private String roomarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_NEU.roomHolderAccount
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    private String roomholderaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_NEU.roomWater
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    private String roomwater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_NEU.roomElectrcity
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    private String roomelectrcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_NEU.roomGas
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    private String roomgas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_NEU.roomEstatefee
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    private String roomestatefee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_NEU.roomHolderName
     *
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    private String roomholdername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_NEU.roomId
     *
     * @return the value of ROOM_NEU.roomId
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public BigDecimal getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_NEU.roomId
     *
     * @param roomid the value for ROOM_NEU.roomId
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setRoomid(BigDecimal roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_NEU.roomBuilding
     *
     * @return the value of ROOM_NEU.roomBuilding
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public String getRoombuilding() {
        return roombuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_NEU.roomBuilding
     *
     * @param roombuilding the value for ROOM_NEU.roomBuilding
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setRoombuilding(String roombuilding) {
        this.roombuilding = roombuilding == null ? null : roombuilding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_NEU.roomFloor
     *
     * @return the value of ROOM_NEU.roomFloor
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public String getRoomfloor() {
        return roomfloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_NEU.roomFloor
     *
     * @param roomfloor the value for ROOM_NEU.roomFloor
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setRoomfloor(String roomfloor) {
        this.roomfloor = roomfloor == null ? null : roomfloor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_NEU.roomDoor
     *
     * @return the value of ROOM_NEU.roomDoor
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public String getRoomdoor() {
        return roomdoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_NEU.roomDoor
     *
     * @param roomdoor the value for ROOM_NEU.roomDoor
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setRoomdoor(String roomdoor) {
        this.roomdoor = roomdoor == null ? null : roomdoor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_NEU.roomArea
     *
     * @return the value of ROOM_NEU.roomArea
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public String getRoomarea() {
        return roomarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_NEU.roomArea
     *
     * @param roomarea the value for ROOM_NEU.roomArea
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setRoomarea(String roomarea) {
        this.roomarea = roomarea == null ? null : roomarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_NEU.roomHolderAccount
     *
     * @return the value of ROOM_NEU.roomHolderAccount
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public String getRoomholderaccount() {
        return roomholderaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_NEU.roomHolderAccount
     *
     * @param roomholderaccount the value for ROOM_NEU.roomHolderAccount
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setRoomholderaccount(String roomholderaccount) {
        this.roomholderaccount = roomholderaccount == null ? null : roomholderaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_NEU.roomWater
     *
     * @return the value of ROOM_NEU.roomWater
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public String getRoomwater() {
        return roomwater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_NEU.roomWater
     *
     * @param roomwater the value for ROOM_NEU.roomWater
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setRoomwater(String roomwater) {
        this.roomwater = roomwater == null ? null : roomwater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_NEU.roomElectrcity
     *
     * @return the value of ROOM_NEU.roomElectrcity
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public String getRoomelectrcity() {
        return roomelectrcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_NEU.roomElectrcity
     *
     * @param roomelectrcity the value for ROOM_NEU.roomElectrcity
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setRoomelectrcity(String roomelectrcity) {
        this.roomelectrcity = roomelectrcity == null ? null : roomelectrcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_NEU.roomGas
     *
     * @return the value of ROOM_NEU.roomGas
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public String getRoomgas() {
        return roomgas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_NEU.roomGas
     *
     * @param roomgas the value for ROOM_NEU.roomGas
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setRoomgas(String roomgas) {
        this.roomgas = roomgas == null ? null : roomgas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_NEU.roomEstatefee
     *
     * @return the value of ROOM_NEU.roomEstatefee
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public String getRoomestatefee() {
        return roomestatefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_NEU.roomEstatefee
     *
     * @param roomestatefee the value for ROOM_NEU.roomEstatefee
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setRoomestatefee(String roomestatefee) {
        this.roomestatefee = roomestatefee == null ? null : roomestatefee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_NEU.roomHolderName
     *
     * @return the value of ROOM_NEU.roomHolderName
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public String getRoomholdername() {
        return roomholdername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_NEU.roomHolderName
     *
     * @param roomholdername the value for ROOM_NEU.roomHolderName
     * @mbggenerated Tue Aug 01 20:04:15 CST 2017
     */
    public void setRoomholdername(String roomholdername) {
        this.roomholdername = roomholdername == null ? null : roomholdername.trim();
    }
}